version: '3.8'

services:
  kb-sits:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kb_sits_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_FILE: /app/data/kb-sits.sqlite
    volumes:
      - kb_sits_data:/app/data

volumes:
  kb_sits_data:
